export const enum Skill {
  NEXT = "Next.js",
  TAILWIND_CSS = "Tailwind CSS",
  TYPESCRIPT = "TypeScript",
  FRAMER_MOTION = "Framer Motion",
  REACT_ICONS = "React Icons",
  REACT_TESTING_LIBRARY = "React Testing Library",
  HERO_UI = "Hero UI",
  ZOD = "Zod",
  ZUSTAND = "Zustand",
  BUN = "Bun",
  AXIOS = "Axios",
  REACT_QUERY = "React Query",
  PYTHON = "Python",
  FASTAPI = "FastAPI",
  POSTGRESQL = "PosgreSQL",
  SQLALCHEMY = "SQLAlchemy",
  PYDANTIC = "Pydantic",
  ALEMBIC = "Alembic",
  UV = "UV",
  UVICORN = "Uvicorn",
  PYDANTIC_SETTINGS = "Pydantic Settings",
  GIT = "Git",
  DOCKER = "Docker",
  REACT_HOOK_FORM = "React Hook Form",
}
